language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.7

install:
 - composer self-update
 - composer install

before_script:
  - php -S localhost:8889 -t public &

script:
  - php vendor/bin/codecept run
